// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJTxFNTLqEV-rcXqcInDBnjeCj9LMjWtc',
    appId: '1:350204746888:web:64a11f38fbd1f1ddc5d33d',
    messagingSenderId: '350204746888',
    projectId: 'lostandfoundmvp',
    authDomain: 'lostandfoundmvp.firebaseapp.com',
    storageBucket: 'lostandfoundmvp.firebasestorage.app',
    measurementId: 'G-N0TT9WK2Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMtNkqXKB2cxzX6hjPSPw8evSNaTVEpZc',
    appId: '1:350204746888:android:4df49869bd7283d9c5d33d',
    messagingSenderId: '350204746888',
    projectId: 'lostandfoundmvp',
    storageBucket: 'lostandfoundmvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnslg1bGD728pF4HsXRTVx5ceC69cM6yU',
    appId: '1:350204746888:ios:3c5304d742361f7ec5d33d',
    messagingSenderId: '350204746888',
    projectId: 'lostandfoundmvp',
    storageBucket: 'lostandfoundmvp.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnslg1bGD728pF4HsXRTVx5ceC69cM6yU',
    appId: '1:350204746888:ios:3c5304d742361f7ec5d33d',
    messagingSenderId: '350204746888',
    projectId: 'lostandfoundmvp',
    storageBucket: 'lostandfoundmvp.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJTxFNTLqEV-rcXqcInDBnjeCj9LMjWtc',
    appId: '1:350204746888:web:3978015341fb7501c5d33d',
    messagingSenderId: '350204746888',
    projectId: 'lostandfoundmvp',
    authDomain: 'lostandfoundmvp.firebaseapp.com',
    storageBucket: 'lostandfoundmvp.firebasestorage.app',
    measurementId: 'G-Z86XR7CSJ9',
  );
}
