// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg9OvnGwjybyZ3pkhXyfsdZoQmm9m2Sxw',
    appId: '1:580036342865:web:13ccd56584e961dd99b470',
    messagingSenderId: '580036342865',
    projectId: 'lost-and-found-app-986a7',
    authDomain: 'lost-and-found-app-986a7.firebaseapp.com',
    storageBucket: 'lost-and-found-app-986a7.firebasestorage.app',
    measurementId: 'G-VG9J24YJWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrsSBclTCJlyHEi0Hy9I0UGQ2JwPNVx98',
    appId: '1:580036342865:android:291c8b0d0600667499b470',
    messagingSenderId: '580036342865',
    projectId: 'lost-and-found-app-986a7',
    storageBucket: 'lost-and-found-app-986a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrdHKwzl7zDj723kPsYsOmW5y9EwmWiIo',
    appId: '1:580036342865:ios:1d827849874df01a99b470',
    messagingSenderId: '580036342865',
    projectId: 'lost-and-found-app-986a7',
    storageBucket: 'lost-and-found-app-986a7.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrdHKwzl7zDj723kPsYsOmW5y9EwmWiIo',
    appId: '1:580036342865:ios:1d827849874df01a99b470',
    messagingSenderId: '580036342865',
    projectId: 'lost-and-found-app-986a7',
    storageBucket: 'lost-and-found-app-986a7.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg9OvnGwjybyZ3pkhXyfsdZoQmm9m2Sxw',
    appId: '1:580036342865:web:443f8796cfbda44699b470',
    messagingSenderId: '580036342865',
    projectId: 'lost-and-found-app-986a7',
    authDomain: 'lost-and-found-app-986a7.firebaseapp.com',
    storageBucket: 'lost-and-found-app-986a7.firebasestorage.app',
    measurementId: 'G-5TYZSF3113',
  );
}
